### ISSUE TITLE
OSError: [Errno 39] Directory not empty

### ISSUE THREAD

**Issue by Layne-Huang** [dptech-corp/Uni-GBSA#33]
Hi,

It is really an excellent work. However, I have met some issues when running your code.
```
File "/nas-alinlp/lhuang/miniconda/envs/gbsa/lib/python3.10/shutil.py", line 729, in rmtree
    os.rmdir(path)
OSError: [Errno 39] Directory not empty: '/ligand_file_name/UNIGBSA'
```
Could you please tell me how to solve it?

**Comment by Aunity** [comment]
Hi, this is a bug of uni-gbsa. You could solve this bug by add the `--verbose`  paras.

**Comment by Layne-Huang** [comment]
Maybe there is another bug. When I ran unigbsa-pipeline, it will throw out:
`    os.chdir(f'{molname}.acpype')
FileNotFoundError: [Errno 2] No such file or directory: 'MOL.acpype'`
However, it successfully ran when I rerun the unigbsa-pipeline.
`05/31/2023 20:48:42 PM - INFO - Build protein topology.
05/31/2023 20:48:44 PM - INFO - Build ligand topology: 7l11_4747
05/31/2023 20:49:07 PM - INFO - Running energy minimization: 7l11_4747
05/31/2023 20:49:13 PM - INFO - Run the MMPB(GB)SA.
05/31/2023 20:49:27 PM - INFO - Clean the results.
================================================================================
Results: Energy.csv Dec.csv
Frames    mode    detal_G(kcal/mole)
     1      gb              -56.8643  `

**Comment by Layne-Huang** [comment]
Besides, it always throw out error when building protein topology:
```
raise Exception('ERROR run gmx! see the log file for details %s'%os.path.abspath("gromacs.log"))
Exception: ERROR run gmx! see the log file for details
```
It also throws out errors when building ligand topology:

```
Traceback (most recent call last):
  File "/miniconda/envs/gbsa/lib/python3.10/site-packages/acpype/cli.py", line 140, in init_main
    molecule.createMolTopol()
  File "/miniconda/envs/gbsa/lib/python3.10/site-packages/acpype/topol.py", line 1116, in createMolTopol
    self.topFileData = open(self.acTopFileName).readlines()
FileNotFoundError: [Errno 2] No such file or directory: 'MOL_AC.prmtop'
Total time of execution: 8s
```

**Comment by Aunity** [comment]
Could you please upload your ligand and protein files? It seems like your ligand do not prepare well.
