### ISSUE TITLE
Failed to generate forcefield for ligand: NADP.

### ISSUE THREAD

**Issue by Tangbbmc** [dptech-corp/Uni-GBSA#54]
(gbsa) dell@dell-OptiPlex-Tower-Plus-7010:~/Videos/unigbsa_NeHSD$ unigbsa-pipeline -i com_rep.pdb -l NADP.mol2 -c default2.ini -o OUTFILE -nt 30 --decomp --verbose 
10/05/2024 17:31:35 PM - INFO - Build protein topology.
10/05/2024 17:31:36 PM - INFO - Build ligand topology: NADP.
export OMP_NUM_THREADS=1;acpype -i /home/dell/Videos/unigbsa_NeHSD/NADP./NADP..mol -b MOL -a gaff -c bcc -n 0 -k "grms_tol=0.005,qm_theory='AM1',scfconv=1.d-8,ndiis_attempts=700,maxcyc=0" -f >acpype.log 2>&1 
============================================================================
| ACPYPE: AnteChamber PYthon Parser interfacE v. 2023.10.27 (c) 2024 AWSdS |
============================================================================
==> ... charge set to 0
==> Executing Antechamber...
ERROR: ++++++++++start_quote+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
ERROR: 
Welcome to antechamber 22.0: molecular input file processor.

Info: The atom type is set to gaff; the options available to the -at flag are
 gaff, gaff2, amber, bcc, and sybyl.

Info: Determining atomic numbers from atomic symbols which are case sensitive.
Running: /home/dell/anaconda3/envs/gbsa/bin/bondtype -j full -i ANTECHAMBER_BOND_TYPE.AC0 -o ANTECHAMBER_BOND_TYPE.AC -f ac
Info: Bond types are assigned for valence state (1) with penalty (1).

Running: /home/dell/anaconda3/envs/gbsa/bin/atomtype -i ANTECHAMBER_AC.AC0 -o ANTECHAMBER_AC.AC -p gaff
Info: Total number of electrons: 381; net charge: 0
Info: The number of electrons is odd (381).
 Please check the total charge (-nc flag) and spin multiplicity (-m flag).

Running: /home/dell/anaconda3/envs/gbsa/bin/sqm -O -i sqm.in -o sqm.out
/home/dell/anaconda3/envs/gbsa/bin/wrapped_progs/antechamber: Fatal Error!
Cannot properly run "/home/dell/anaconda3/envs/gbsa/bin/sqm -O -i sqm.in -o sqm.out".

ERROR: ++++++++++end_quote+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
ERROR: Antechamber failed
ERROR: ++++++++++start_quote+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
ERROR: Cannot open file (MOL_bcc_gaff.mol2) with mode (r).
No such file or directory
ERROR: ++++++++++end_quote+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
ERROR: Parmchk failed
ERROR: Tleap failed
==> Removing temporary files...
ERROR: ACPYPE FAILED: [Errno 2] No such file or directory: 'MOL_AC.prmtop'
Traceback (most recent call last):
  File "/home/dell/anaconda3/envs/gbsa/lib/python3.12/site-packages/acpype/cli.py", line 138, in init_main
    molecule.createMolTopol()
  File "/home/dell/anaconda3/envs/gbsa/lib/python3.12/site-packages/acpype/topol.py", line 1115, in createMolTopol
    self.topFileData = open(self.acTopFileName).readlines()
                       ^^^^^^^^^^^^^^^^^^^^^^^^
FileNotFoundError: [Errno 2] No such file or directory: 'MOL_AC.prmtop'
Total time of execution: less than a second
Traceback (most recent call last):
  File "/home/dell/anaconda3/envs/gbsa/lib/python3.12/site-packages/unigbsa/pipeline.py", line 139, in single
    build_topol(receptor, ligandfile, outpdb=grofile, outtop=topfile,
  File "/home/dell/anaconda3/envs/gbsa/lib/python3.12/site-packages/unigbsa/simulation/topology.py", line 219, in build_topol
    moltop, molgro = build_lignad(ligand, forcefield=ligandforce, charge_method=charge_method, nt=nt, verbose=verbose)
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/dell/anaconda3/envs/gbsa/lib/python3.12/site-packages/unigbsa/simulation/topology.py", line 68, in build_lignad
    raise Exception('ERROR run the acpype. see the %s for details.'%os.path.abspath("acpype.log"))
Exception: ERROR run the acpype. see the /home/dell/Videos/unigbsa_ZaHSD/NADP./NADP..TOP/acpype.log for details.
10/05/2024 17:31:36 PM - WARNING - Failed to generate forcefield for ligand: NADP.
[NADP.zip](https://github.com/user-attachments/files/17265702/NADP.zip)

**Comment by Aunity** [comment]
Please check your ligand's  formal charge. And you can use the `unigbsa-validate` to fix this problem.
```
unigbsa-validate -i NADP.mol2 -o NADP.sdf
```
Please double check the output sdf file.
![image](https://github.com/user-attachments/assets/c2932a13-94be-4d73-ad49-386ec6b4d846)
