### ISSUE TITLE
I would like to simplify the file preparation for MD with unigbsa. What should I do?

### ISSUE THREAD

**Issue by Tangbbmc** [dptech-corp/Uni-GBSA#56]
It is well-known that preparing the files for molecular dynamic (MD) simulation of protein-ligand complex is a tedious process, which includes preparing ligand topology, solvation, adding ions,  energy minimization, equilibration, and so on. Could I simplify the file preparation for 100-ns gromacs MD run of one protein-ligand complex with unigbsa?

**Comment by Aunity** [comment]
Yes, you can just use the command `unigbsa-md` to do that, here is an example:
```
unigbsa-md -p 1ceb_protein.pdb -l 1ceb_ligand.sdf -pf amber99sb -lf gaff -bt cubic -d 1.0 -conc 0.15 -o md-100ns -nsteps 50000000 -nframe  10000 -nt 16
```

**Comment by Tangbbmc** [comment]
Great! Thank you very much for your reply! I love your software very much! However, I have some questions. The command unigbsa-md did not mention water model. Which water model will be selected for md simulation? Except for amber99sb force field for protein and -gaff force field for ligand, can I select other force fields for protein and ligand? I have installed GPU version of Gromac2024 on Ubuntu system? I hope that unigbsa invokes Gromacs2024 to speed simulation. What should I do? Finally, I run the following command based on your provided example, however some error happened. Could you give me some suggestions to solve this question? I am looking forward to your reply as soon as possible!

(gbsa) ***@***.***:~/Final_NADP$ unigbsa-md -p com_rep.pdb -l final_NAP.mol2 -pf amber99sb -lf gaff -bt cubic -d 1.0 -conc 0.15 -o md-50ns -nsteps 25000000 -nframe 500 -nt 30
10/18/2024 23:08:30 PM - INFO - Build ligand topology: final_NAP.
10/18/2024 23:08:32 PM - INFO - Building simulation for: final_NAP.
gmx mdrun -v -deffnm nvt -nt 30 -ntmpi 1
 bonds that rotated more than 30 degrees:
 atom 1 atom 2 angle previous, current, constraint length
 3 32 90.0 0.3281 0.2211 0.0973
 1 16 67.6 0.0973 0.0973 0.0973
 2 20 90.0 0.1290 0.1202 0.0973
Wrote pdb files with previous and current coordinates

Step 169, time 0.338 (ps) LINCS WARNING
relative constraint deviation after LINCS:
rms 0.045649, max 2.363351 (between atoms 3 and 32)
bonds that rotated more than 30 degrees:
 atom 1 atom 2 angle previous, current, constraint length
 3 32 90.0 0.2211 0.3273 0.0973
 1 16 75.6 0.0973 0.0973 0.0973
 2 20 90.0 0.1202 0.1286 0.0973
Wrote pdb files with previous and current coordinates

Step 170, time 0.34 (ps) LINCS WARNING
relative constraint deviation after LINCS:
rms 0.026447, max 1.358207 (between atoms 3 and 32)
bonds that rotated more than 30 degrees:
 atom 1 atom 2 angle previous, current, constraint length
 3 32 90.0 0.3273 0.2295 0.0973
 1 16 63.6 0.0973 0.0973 0.0973
 2 20 90.0 0.1286 0.1221 0.0973
Wrote pdb files with previous and current coordinates

Step 171, time 0.342 (ps) LINCS WARNING
relative constraint deviation after LINCS:
rms 0.157090, max 8.201681 (between atoms 3 and 32)
bonds that rotated more than 30 degrees:
 atom 1 atom 2 angle previous, current, constraint length
 3 32 90.0 0.2295 0.8953 0.0973
 1 16 71.7 0.0973 0.0973 0.0973
 2 20 90.0 0.1221 0.1282 0.0973
Wrote pdb files with previous and current coordinates

Step 172, time 0.344 (ps) LINCS WARNING
relative constraint deviation after LINCS:
rms 32.763947, max 1711.896606 (between atoms 3 and 32)
bonds that rotated more than 30 degrees:
 atom 1 atom 2 angle previous, current, constraint length
 3 32 122.9 0.8953 166.6649 0.0973
 1 16 69.3 0.0973 0.0973 0.0973
 2 20 90.0 0.1282 0.1232 0.0973

step 172: One or more water molecules can not be settled.
Check for bad contacts and/or reduce the timestep if appropriate.
Wrote pdb files with previous and current coordinates
Segmentation fault (core dumped)
Traceback (most recent call last):
 File "/home/dell/anaconda3/envs/gbsa/bin/unigbsa-md", line 8, in <module>
 sys.exit(simulation_run())
 ^^^^^^^^^^^^^^^^
 File "/home/dell/anaconda3/envs/gbsa/lib/python3.12/site-packages/unigbsa/CLI.py", line 231, in simulation_run
 mdgro, mdxtc, topfile = engine.run_to_md(grofile, topfile, rundir=None, boxtype=boxtype, boxsize=boxsize, conc=conc, nsteps=nsteps, nframe=nframe, nt=nt)
 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
 File "/home/dell/anaconda3/envs/gbsa/lib/python3.12/site-packages/unigbsa/simulation/mdrun.py", line 446, in run_to_md
 nptpdb, topfile = self.run_to_npt(pdbfile, topfile, rundir=rundir, boxtype=boxtype, boxsize=boxsize, maxsol=maxsol, conc=conc, nsteps=eqsteps, nt=nt)
 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
 File "/home/dell/anaconda3/envs/gbsa/lib/python3.12/site-packages/unigbsa/simulation/mdrun.py", line 425, in run_to_npt
 nvtpdb = self.gmx_nvt(minipdb, topfile, mdpfile=os.path.join(MDPFILESDIR, 'nvt.mdp'), nsteps=nsteps, nt=nt)
 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
 File "/home/dell/anaconda3/envs/gbsa/lib/python3.12/site-packages/unigbsa/simulation/mdrun.py", line 273, in gmx_nvt
 outfile = self._mdrun(outtpr, nt, nsteps=nsteps)
 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
 File "/home/dell/anaconda3/envs/gbsa/lib/python3.12/site-packages/unigbsa/simulation/mdrun.py", line 80, in _mdrun
 raise Exception('ERROR run mdrun %s. See the logfile for details %s'%(tprfile, os.path.abspath(self.gmxlog)))






唐王刚 Wanggang Tang
博士 副教授 
Ph.D.  Associate Professor
Address: No. 2600, Donghai Avenue. Bengbu, Anhui, China
Alternative email address: ***@***.***
Institution homepage: https://www.bbmc.edu.cn/



发件人：Maohua Yang ***@***.***>
发送日期：2024-10-16 18:07:45
收件人：dptech-corp/Uni-GBSA ***@***.***>
抄送人：Wanggang ***@***.***>,Author ***@***.***>
主题：Re: [dptech-corp/Uni-GBSA] I would like to simplify the file preparation for MD with unigbsa. What should I do? (Issue #56)

Yes, you can just use the command unigbsa-md to do that, here is an example:
unigbsa-md -p 1ceb_protein.pdb -l 1ceb_ligand.sdf -pf amber99sb -lf gaff -bt cubic -d 1.0 -conc 0.15 -o md-100ns -nsteps 50000000 -nframe  10000 -nt 16

**Comment by Aunity** [comment]
By default, Uni-GBSA use the TIP3P water model. 

You can choose any protein forcefield in your gromacs. But you need to use the correct protein forcefile name in your gromacs `***/share/gromacs/top` path. We recomand you choose the AMBER forcefield for protein cause we just support gaff/gaff2 forcefield for ligands.
![image](https://github.com/user-attachments/assets/458fea92-95fc-4836-864b-6fd51b317a8b)

If you want to use the Gromacs installed by yourself. You need to remove the gromacs installed by conda by command ` conda uninstall gromacs`. And then load the Gromacs2024 by source the GMXRC.bash file: `source /xxx/gmx2024/bin/GMXRC.bash`

As for your error, it seems your structure have some clash problem. You need to check if your structure has serious crashes

**Comment by Tangbbmc** [comment]
I am very pleased to receive your reply. If I use Gromacs (gpu version) installed by myself to execute unigbsa-md, can I use gpu acceleration of gromacs? Moreover, could I simulate antibody-antigen complex using unigbsa-md? I am looking forward to your reply as soon as possible!

From: Maohua Yang ***@***.***>
Date: 2024-10-25 16:49:18
To: dptech-corp/Uni-GBSA ***@***.***>
Cc: Wanggang ***@***.***>,Author ***@***.***>
Subject: Re: [dptech-corp/Uni-GBSA] I would like to simplify the file preparation for MD with unigbsa. What should I do? (Issue #56)

By default, Uni-GBSA use the TIP3P water model.
You can choose any protein forcefield in your gromacs. But you need to use the correct protein forcefile name in your gromacs ***/share/gromacs/top path. We recomand you choose the AMBER forcefield for protein cause we just support gaff/gaff2 forcefield for ligands.
 image.png (view on web)
If you want to use the Gromacs installed by yourself. You need to remove the gromacs installed by conda by command conda uninstall gromacs. And then load the Gromacs2024 by source the GMXRC.bash file: source /xxx/gmx2024/bin/GMXRC.bash
As for your error, it seems your structure have some clash problem. You need to check if your structure has serious crashes

**Comment by Tangbbmc** [comment]
I forgot to answer another question. If the modelled structure that has crashes, how do I solve or repair this question?


---- Replied Message ----
From  Maohua ***@***.***> Date  10/25/2024 16:49 To  ***@***.***> Cc  ***@***.***>***@***.***> Subject  Re: [dptech-corp/Uni-GBSA] I would like to simplify the file preparation for MD with unigbsa. What should I do? (Issue #56)  

By default, Uni-GBSA use the TIP3P water model.
You can choose any protein forcefield in your gromacs. But you need to use the correct protein forcefile name in your gromacs ***/share/gromacs/top path. We recomand you choose the AMBER forcefield for protein cause we just support gaff/gaff2 forcefield for ligands.
 image.png (view on web)
If you want to use the Gromacs installed by yourself. You need to remove the gromacs installed by conda by command conda uninstall gromacs. And then load the Gromacs2024 by source the GMXRC.bash file: source /xxx/gmx2024/bin/GMXRC.bash
As for your error, it seems your structure have some clash problem. You need to check if your structure has serious crashes

**Comment by Aunity** [comment]
Yes, in that way. You can use the GPU accelerated gromacs. Unigbsa version 0.1.7 support protein protein complex simulation, so you can try it by setting the -lf parameter with a pdb file of antigen and setting the -pf parameter with a pdb file of antibody.

在 2024年10月25日，20:58，Wanggang ***@***.***> 写道：

﻿

I forgot to answer another question. If the modelled structure that has crashes, how do I solve or repair this question?


---- Replied Message ----
From Maohua ***@***.***> Date 10/25/2024 16:49 To ***@***.***> Cc ***@***.***>***@***.***> Subject Re: [dptech-corp/Uni-GBSA] I would like to simplify the file preparation for MD with unigbsa. What should I do? (Issue #56)

By default, Uni-GBSA use the TIP3P water model.
You can choose any protein forcefield in your gromacs. But you need to use the correct protein forcefile name in your gromacs ***/share/gromacs/top path. We recomand you choose the AMBER forcefield for protein cause we just support gaff/gaff2 forcefield for ligands.
image.png (view on web)
If you want to use the Gromacs installed by yourself. You need to remove the gromacs installed by conda by command conda uninstall gromacs. And then load the Gromacs2024 by source the GMXRC.bash file: source /xxx/gmx2024/bin/GMXRC.bash
As for your error, it seems your structure have some clash problem. You need to check if your structure has serious crashes

**Comment by Tangbbmc** [comment]
OK. When I hope unigbasa to run the GPU accelerated gromacs, do I need to add "-nb gpu" flag when executing unigbsa-md command?

发件人：Maohua Yang ***@***.***>
发送日期：2024-10-25 21:33:13
收件人：dptech-corp/Uni-GBSA ***@***.***>
抄送人：Wanggang ***@***.***>,Author ***@***.***>
主题：Re: [dptech-corp/Uni-GBSA] I would like to simplify the file preparation for MD with unigbsa. What should I do? (Issue #56)


Yes, in that way. You can use the GPU accelerated gromacs. Unigbsa version 0.1.7 support protein protein complex simulation, so you can try it by setting the -lf parameter with a pdb file of antigen and setting the -pf parameter with a pdb file of antibody.

 在 2024年10月25日，20:58，Wanggang ***@***.***> 写道：

 ﻿

 I forgot to answer another question. If the modelled structure that has crashes, how do I solve or repair this question?


 ---- Replied Message ----
 From Maohua ***@***.***> Date 10/25/2024 16:49 To ***@***.***> Cc ***@***.***>***@***.***> Subject Re: [dptech-corp/Uni-GBSA] I would like to simplify the file preparation for MD with unigbsa. What should I do? (Issue #56)

 By default, Uni-GBSA use the TIP3P water model.
 You can choose any protein forcefield in your gromacs. But you need to use the correct protein forcefile name in your gromacs ***/share/gromacs/top path. We recomand you choose the AMBER forcefield for protein cause we just support gaff/gaff2 forcefield for ligands.
 image.png (view on web)
 If you want to use the Gromacs installed by yourself. You need to remove the gromacs installed by conda by command conda uninstall gromacs. And then load the Gromacs2024 by source the GMXRC.bash file: source /xxx/gmx2024/bin/GMXRC.bash
 As for your error, it seems your structure have some clash problem. You need to check if your structure has serious crashes

**Comment by Aunity** [comment]
Sorry, additional gpu parameters (like -nb gpu) are not supported now.

**Comment by Tangbbmc** [comment]
Without the addition of gpu parameters, can unigbsa-md also execute the gpu acceleration when running gromacs2024 (gpu version)?

发件人：Maohua Yang ***@***.***>
发送日期：2024-10-25 22:12:03
收件人：dptech-corp/Uni-GBSA ***@***.***>
抄送人：Wanggang ***@***.***>,Author ***@***.***>
主题：Re: [dptech-corp/Uni-GBSA] I would like to simplify the file preparation for MD with unigbsa. What should I do? (Issue #56)

Sorry, additional gpu parameters (like -nb gpu) are not supported now.

**Comment by Aunity** [comment]
Yes, gromacs will use the GPU accelation when you compile the gromacs with cuda support. The parameters like `-nb gpu` mean put more computation on GPU. It will faster when you add the parameters like `-nb gpu` than without these parameters added, but it still will use the GPU accelation and more faster than the graomacs only with cpu.

**Comment by Tangbbmc** [comment]
OK. I get! Thank you very much for your patient explannation. I would like to consult a question. Can unigbsa-md perform molecular dynamic simulation for receptor containing zinc ions?

发件人：Maohua Yang ***@***.***>
发送日期：2024-10-25 22:53:02
收件人：dptech-corp/Uni-GBSA ***@***.***>
抄送人：Wanggang ***@***.***>,Author ***@***.***>
主题：Re: [dptech-corp/Uni-GBSA] I would like to simplify the file preparation for MD with unigbsa. What should I do? (Issue #56)

Yes, gromacs will use the GPU accelation when you compile the gromacs with cuda support. The parameters like -nb gpu mean put more computation on GPU. It will faster when you add the parameters like -nb gpu than without these parameters added, but it still will use the GPU accelation and more faster than the graomacs only with cpu.

**Comment by Tangbbmc** [comment]
Dear Prof. Yang,
   I performed a MD simulation of antigen-antibody complex, termed rep.pdb, with unigbsa-md (unigbsa-md -p rep.pdb -pf amber99sb -bt triclinic -d 1.0 -conc 0.15 -o md-100ns -nsteps 50000000 -nframe  500 -nt 30 -verbose) . However, the previously reported error (see below) appeared again. I have uploaded the structure of complex. Could you help me check the problem? It is worth mentioned that this complex structure has been successfully used to perform 100-ns MD simulation with Gromacs2024 installed by myself with all-atom OPLS force field. This seems to suggest that there are not crashes observed in the start complex structure. I am looking forward to your reply as soon as possible!





Error report:
Traceback (most recent call last):
  File "/home/dell/anaconda3/envs/gbsa/bin/unigbsa-md", line 8, in <module>
    sys.exit(simulation_run())
             ^^^^^^^^^^^^^^^^
  File "/home/dell/anaconda3/envs/gbsa/lib/python3.12/site-packages/unigbsa/CLI.py", line 209, in simulation_run
    mdgro, mdxtc, topfile = engine.run_to_md(grofile, topfile, rundir=None, boxtype=boxtype, boxsize=boxsize, conc=conc, nsteps=nsteps, nframe=nframe, nt=nt)
                            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/dell/anaconda3/envs/gbsa/lib/python3.12/site-packages/unigbsa/simulation/mdrun.py", line 451, in run_to_md
    mdxtcpbc = process_pbc(mdxtc, 'md.tpr', indexfile=indexfile, logfile=self.gmxlog)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/dell/anaconda3/envs/gbsa/lib/python3.12/site-packages/unigbsa/utils.py", line 128, in process_pbc
    raise Exception('Process pbc error: see the %s file for details'%logfile)



唐王刚 Wanggang Tang
博士 副教授 
Ph.D.  Associate Professor
Address: No. 2600, Donghai Avenue. Bengbu, Anhui, China
Alternative email address: ***@***.***
Institution homepage: https://www.bbmc.edu.cn/



发件人：Maohua Yang ***@***.***>
发送日期：2024-10-25 21:33:13
收件人：dptech-corp/Uni-GBSA ***@***.***>
抄送人：Wanggang ***@***.***>,Author ***@***.***>
主题：Re: [dptech-corp/Uni-GBSA] I would like to simplify the file preparation for MD with unigbsa. What should I do? (Issue #56)


Yes, in that way. You can use the GPU accelerated gromacs. Unigbsa version 0.1.7 support protein protein complex simulation, so you can try it by setting the -lf parameter with a pdb file of antigen and setting the -pf parameter with a pdb file of antibody.

 在 2024年10月25日，20:58，Wanggang ***@***.***> 写道：

 ﻿

 I forgot to answer another question. If the modelled structure that has crashes, how do I solve or repair this question?


 ---- Replied Message ----
 From Maohua ***@***.***> Date 10/25/2024 16:49 To ***@***.***> Cc ***@***.***>***@***.***> Subject Re: [dptech-corp/Uni-GBSA] I would like to simplify the file preparation for MD with unigbsa. What should I do? (Issue #56)

 By default, Uni-GBSA use the TIP3P water model.
 You can choose any protein forcefield in your gromacs. But you need to use the correct protein forcefile name in your gromacs ***/share/gromacs/top path. We recomand you choose the AMBER forcefield for protein cause we just support gaff/gaff2 forcefield for ligands.
 image.png (view on web)
 If you want to use the Gromacs installed by yourself. You need to remove the gromacs installed by conda by command conda uninstall gromacs. And then load the Gromacs2024 by source the GMXRC.bash file: source /xxx/gmx2024/bin/GMXRC.bash
 As for your error, it seems your structure have some clash problem. You need to check if your structure has serious crashes

**Comment by Aunity** [comment]
In the Complex.GMX floder have a gromacs.log file. You can check it to see the details.

**Comment by Tangbbmc** [comment]
The following error was found in gromacs.log file.
 Fatal error:
Index[9411] 92818 is larger than the number of atoms in the
trajectory file (9591). There is a mismatch in the contents
of your -f, -s and/or -n files.

For more information and tips for troubleshooting, please check the GROMACS
website at https://manual.gromacs.org/current/user-guide/run-time-errors.html
-------------------------------------------------------
Note that major changes are planned in future for trjconv, to improve usability and utility.
Select group for centering
Selected 18: 'center'
Select group for output
Selected 19: 'output'

发件人：Maohua Yang ***@***.***>
发送日期：2024-10-27 22:26:49
收件人：dptech-corp/Uni-GBSA ***@***.***>
抄送人：Wanggang ***@***.***>,Author ***@***.***>
主题：Re: [dptech-corp/Uni-GBSA] I would like to simplify the file preparation for MD with unigbsa. What should I do? (Issue #56)

In the Complex.GMX floder have a gromacs.log file. You can check it to see the details.

**Comment by Tangbbmc** [comment]
Moreover, I checked the trajectory file and found that some frames displayed serious distorted structures (see attached png file).






唐王刚 Wanggang Tang
博士 副教授 
Ph.D.  Associate Professor
Address: No. 2600, Donghai Avenue. Bengbu, Anhui, China
Alternative email address: ***@***.***
Institution homepage: https://www.bbmc.edu.cn/



发件人：Maohua Yang ***@***.***>
发送日期：2024-10-27 22:26:49
收件人：dptech-corp/Uni-GBSA ***@***.***>
抄送人：Wanggang ***@***.***>,Author ***@***.***>
主题：Re: [dptech-corp/Uni-GBSA] I would like to simplify the file preparation for MD with unigbsa. What should I do? (Issue #56)

In the Complex.GMX floder have a gromacs.log file. You can check it to see the details.

**Comment by Aunity** [comment]
Sorry, I did not see your attached png file. You can join our wechat group to get quick reply.
![img_v3_02g6_d3fed7d6-3de4-4073-b291-b5c368c6862g](https://github.com/user-attachments/assets/f1f133ab-87be-4524-934c-ebb7f12fb2ff)

**Comment by Tangbbmc** [comment]
> Sorry, I did not see your attached png file. You can join our wechat group to get quick reply. ![img_v3_02g6_d3fed7d6-3de4-4073-b291-b5c368c6862g](https://private-user-images.githubusercontent.com/18044835/381856546-f1f133ab-87be-4524-934c-ebb7f12fb2ff.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzA0MjI2ODIsIm5iZiI6MTczMDQyMjM4MiwicGF0aCI6Ii8xODA0NDgzNS8zODE4NTY1NDYtZjFmMTMzYWItODdiZS00NTI0LTkzNGMtZWJiN2YxMmZiMmZmLmpwZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMDElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTAxVDAwNTMwMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWVjZGY4ZmM3MzY2MjdhZWE2OWI3ZTA5YWY5ZDVjMDFlYmRkMWE3MWViOGY4MjRjOGQxNjdiNjNmYjk3ZGVhNDYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.cSrb_4c098V584yYn8-YhCOEaTx-51S68vxAsTkTvH4)

![trajectory](https://github.com/user-attachments/assets/48ee97c3-9d52-4565-b344-eaaf77ce38df)
I have uploaded the png file again!   And I have joined your wechat group!

**Comment by Aunity** [comment]
Can you share you input pdb file and the MD final frame structures? It seems the problem of pymol visualization.

**Comment by Tangbbmc** [comment]
[file_TWG.zip](https://github.com/user-attachments/files/17634700/file_TWG.zip)
@Aunity Please find the files.
The command used:
unigbsa-md -p complex.pdb -pf amber99sb -bt triclinic -d 1.0 -conc 0.15 -o md-100ns -nsteps 50000000 -nframe  500 -nt 30 -verbose

**Comment by Aunity** [comment]
The serious distorted structures in your trajector were caused by the PBC condition and incorrect pdb format. Here the green is the last frame which I fixed the pbc condition and the purple one is the last frame which I used the correct pdb format.

[fixed-pdbs.zip](https://github.com/user-attachments/files/17643479/fixed-pdbs.zip)

![image](https://github.com/user-attachments/assets/84f6fa4a-0074-411d-bf57-41f090f0be45)
