### ISSUE TITLE
The resulting .xtc file from unigbsa-md had not water molecules and ions.

### ISSUE THREAD

**Issue by Tangbbmc** [dptech-corp/Uni-GBSA#58]
The resulting .xtc file from unigbsa-md had not water molecules and ions. How to include water molecules and ions in .xtc file. Moreover, when processing  pbc with unigbsa-pbc command, I received the following error:

(gbsa) dell@dell-OptiPlex-Tower-Plus-7010:~/Downloads/Uni-GBSA-master/example/1ceb$ unigbsa-pbc -s md.tpr -f md-pbc.xtc -o md-nopbc.xtc -n index.ndx 
gmx trjconv -s md.tpr -n index.ndx -f md-pbc.xtc -o md-pbc-1.xtc -pbc mol -ur compact >> /dev/null 2>&1 << EOF
    output
EOF
Traceback (most recent call last):
  File "/home/dell/anaconda3/envs/gbsa/bin/unigbsa-pbc", line 8, in <module>
    sys.exit(PBC_main())
             ^^^^^^^^^^
  File "/home/dell/anaconda3/envs/gbsa/lib/python3.12/site-packages/unigbsa/CLI.py", line 31, in PBC_main
    process_pbc(trajfile, tprfile, indexfile=indexfile, outfile=outfile)
  File "/home/dell/anaconda3/envs/gbsa/lib/python3.12/site-packages/unigbsa/utils.py", line 117, in process_pbc
    raise Exception('Process pbc error: see the %s file for details'%logfile)
Exception: Process pbc error: see the /dev/null file for details

**Comment by Aunity** [comment]
You can save all files during the MD process by adding the `-verbose` parameter. And the `outdir/complex.GMX/md.xtc` is the trajectory contains the water molecules and ions. As for the error you mentioned, could you please provide all the files you run（md.tpr, md-pbc.xtc and index.ndx）?

**Comment by Tangbbmc** [comment]
Ok. I am very glad to receive your reply! Could you further introduce the differences among md.xtc, md-pbc.xtc, and traj_comx.xtc? Does traj_comx.txc have removed PBC?

发件人：Maohua Yang ***@***.***>
发送日期：2024-10-25 16:34:52
收件人：dptech-corp/Uni-GBSA ***@***.***>
抄送人：Wanggang ***@***.***>,Author ***@***.***>
主题：Re: [dptech-corp/Uni-GBSA] The resulting .xtc file from unigbsa-md had not water molecules and ions. (Issue #58)

You can save all files during the MD process by adding the -verbose parameter. And the outdir/complex.GMX/md.xtc is the trajectory contains the water molecules and ions. As for the error you mentioned, could you please provide all the files you run（md.tpr, md-pbc.xtc and index.ndx）?

**Comment by Aunity** [comment]
The `md.xtc` file is the original output trajectory file of the md production. The `md-pbc.xtc` and the `traj_comx.xtc` file are the same file in different floder and name. The `md-pbc.xtc` file is the `md.xtc` file with PBC removed, and the `traj_comx.xtc` is a copy of `md-pbc.xtc` file.

**Comment by Tangbbmc** [comment]
I see. Thank you very much for your advice.

发件人：Maohua Yang ***@***.***>
发送日期：2024-10-25 21:54:23
收件人：dptech-corp/Uni-GBSA ***@***.***>
抄送人：Wanggang ***@***.***>,Author ***@***.***>
主题：Re: [dptech-corp/Uni-GBSA] The resulting .xtc file from unigbsa-md had not water molecules and ions. (Issue #58)

The md.xtc file is the original output trajectory file of the md production. The md-pbc.xtc and the traj_comx.xtc file are the same file in different floder and name. The md-pbc.xtc file is the md.xtc file with PBC removed, and the traj_comx.xtc is a copy of md-pbc.xtc file.
